name: 'Cancel Prev Run Workflow'
description: 'This Action will cancel any previous runs that are not `completed` for a given workflow.'
author: optimaxdev
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  workflow_id:
    description: 'Optional - A single Workflow ID or a comma separated list of IDs'
    required: false
  github-token:
    description: 'Your GitHub Access Token, ie: {{ secrets.GH_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'