name: Cancel Self

on: [push]

jobs:
  task:
    runs-on: ubuntu-latest
    name: Task
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up BATS
        run: yarn
      - name: Compilation
        run: tsc
      - name: Test Step
        uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{ github.token }}
      - uses: actions/setup-node@v1
      - run: echo 'Sleeping...'; sleep 120; echo 'Done.';
